### ISSUE TITLE
Better detection of invalid geo coordinates

### ISSUE THREAD

**Issue by opatut** [openbikesensor/OpenBikeSensor-Scripts#10]
Apparently sometimes the geo coordinates are invalid but that is not properly detected. Example:

![image](https://user-images.githubusercontent.com/235784/118161958-7df39280-b420-11eb-9af1-0f40fc5b3296.png)

Those should be filtered out.

The file starts like this, and after a few lines switches to proper coordinates

```
Date;Time;Latitude;Longitude;Course;Speed;Right;Left;Confirmed;insidePrivacyArea
25.08.2020;14:21:53;0.000000;0.000000;0.000;0.0000;255;255;0;0
```

**Comment by FlorusCiphersmith** [comment]
I just committed a change that marks positions as invalid if latitude==longitude==0.0, but only for the "old" format (before introducing the metadata).

**Comment by amandel** [comment]
The problem also appears with the current csv `OBSDataFormat=2`  if there are empty `Latitude` / `Longitude` entries. This happens if you start recording before a full GPS fix.

**Comment by FlorusCiphersmith** [comment]
For format version 2, Latitude/Longitude are both marked as invalid, if at least one of them is empty, not a valid number, NaN, or outside the range ( [-90,+90], [-180,+180]). Latitude=Longitude=0.0, however, is accepted.

Does this cover the privacy area/NoPosition case? I understand that in this case, Latitude and Longitude are empty and thus will be marked as invalid.

Are there more cases we should check, or can we close the issue?

**Comment by amandel** [comment]
Yes the case where there is no fix is handled the same way as if you are in a privacy area - the GPS values are left empty. So it should be fine as you describe it.

**Comment by opatut** [comment]
* `Latitude == 0 OR Longitude == 0` should be accepted
* `Latitude == 0 AND Longitude == 0` should be rejected

**Comment by FlorusCiphersmith** [comment]
For formats _before_ v2, the data is handled as described by @opatut.

For the v2 format, `Latitude==Longitude==0` is handled as a valid position, as I understand the [format specification(https://github.com/openbikesensor/OpenBikeSensorFirmware/blob/master/docs/software/firmware/csv_format.md) to allow this combination.

Shall we change the v2 import behavior (and the format specification)?

**Comment by opatut** [comment]
You're refering to this?

> If there is no value in an entry this means no measurement or not available or hidden. Before we used -1 or NaN for this, now we are less polite and save the space.

I would be pragmatic here and just extend the interpretation of inputs to ignore `0|0` entries as well, even if the spec says it should be as empty cells in the CSV and somebody or some tool wrote `0;0` into it instead. Let's try to be accurate when writing files according to spec, but be forgiving when interpreting files.
