### ISSUE TITLE
Support other countries than Germany

### ISSUE THREAD

**Issue by opatut** [openbikesensor/OpenBikeSensor-Scripts#12]
Obviously, we're querying for only German road segments here.

https://github.com/openbikesensor/OpenBikeSensor-Scripts/blob/e79a269d0ead46081c18a99dd30faaf8eaced267/obs/face/osm/DataSource.py#L43

Make sure that this also works if you live somewhere else. Might be solved through #7 though, if that uses non-semantic/geometric regions for downloading.

**Comment by FlorusCiphersmith** [comment]
All dependencies on the region of Germany have been removed. It should now work equally well for all regions on earth.
