### ISSUE TITLE
Auto-detect regions to download from Overpass

### ISSUE THREAD

**Issue by opatut** [openbikesensor/OpenBikeSensor-Scripts#7]
Right now we have to manually specify the districts to download from the overpass API for road segment matching.

This won't be feasible if the Portal is to automatically annotate all uploaded tracks.

I therefore suggest a mechanism to automatically detect boundaries (geometric or administrative) to download the data from, based on the geocoordinates of the input data.

**Comment by FlorusCiphersmith** [comment]
The dependency on user-provided district was replaced by automatic downloading of map parts in the shape of OSM-like tiles.
The -D parameter is now obsolete.
